#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but the 9th iteration should display "Best School" and then "Hi
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
